### ISSUE TITLE
no fabric 1.19.2

### ISSUE THREAD

**Issue by bombaatomowa123456** [VegaKey/Fumo#1]
MAKE FABRIC 1.19.2 PLEASE ITS THE ONLY VERSION I COULD USE

**Comment by NathanLithia** [comment]
> MAKE FABRIC 1.19.2 PLEASE ITS THE ONLY VERSION I COULD USE

Unless you want to port this to 1.19.2 I can only make 1.20.1 fabric versions sorry.
[https://mcreator.net/plugin/64512/mcreator-fabric-generator](https://mcreator.net/plugin/64512/mcreator-fabric-generator)

I am working on a second mod though on a different framework that should allow compilation on all versions but that wont be coming out any time soon unfortunately.
